### ISSUE TITLE
Sensor information of the "player" TORCS agent

### ISSUE THREAD

**Issue by MehaKaushik** [abhisheknaik96/MultiAgentTORCS#1]
Hey, 

Is it possible to extract the sensor data(as mentioned [here](http://xed.ch/help/torcs.html) in section SENSOR ) of the inbuilt "player" agent of TORCS.

**Comment by abhisheknaik96** [comment]
The `scr_server` communicates with the agent over a UDP channel.<sup>1</sup> The function `drive()` in `torcs-x.x.x/src/drivers/scr_server/scr_server.cpp` receives the action in the form of a string from the agent, which is then parsed into the action action inputs before being applied by the game engine to get the next state.     

One way to extract the sensor data would be to get these action inputs via the keyboard, as is done in `torcs-x.x.x/src/drivers/human/human.cpp`. You can copy-paste that keyboard/joystick input code in place of the UDP-string-parsing in `scr_server.cpp` in order to manually collect data from the simulator.

Hope that answers your question.     

<sub>
1 <a href="https://pdfs.semanticscholar.org/9b1d/e5d93854d9dc364a4bc6a462193ccc3ea895.pdf">SCR-manual</a> (Pages 2-3)
</sub>

**Comment by MehaKaushik** [comment]
Yes it does. Thanks.
